# Generated by Django 4.1.7 on 2023-03-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter seller name', max_length=30)),
                ('time_open', models.DateField(blank=True, null=True, verbose_name='Open')),
                ('time_close', models.DateField(blank=True, null=True, verbose_name='Close')),
            ],
        ),
    ]
