# Generated by Django 4.1.7 on 2023-03-05 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter pizza name', max_length=100)),
                ('dough', models.CharField(help_text='Enter dough name', max_length=100)),
                ('sauce', models.CharField(help_text='Enter sauce name', max_length=100)),
                ('filling', models.CharField(help_text='Enter filling name', max_length=100)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(max_length=10)),
                ('time_order', models.DateField(blank=True, null=True, verbose_name='Time order')),
                ('list_pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pizza')),
            ],
        ),
    ]
