# Generated by Django 4.1.7 on 2023-03-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_pizza_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='dough',
        ),
        migrations.AddField(
            model_name='pizza',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Think'), ('2', 'Medium'), ('3', 'Thin')], default='2', help_text='Choose dough', max_length=1),
        ),
    ]
