# Generated by Django 4.1.7 on 2023-03-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_pizza_status_salesman_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='last_name',
            field=models.CharField(blank=True, help_text='Enter seller name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salesman',
            name='second_name',
            field=models.CharField(blank=True, help_text='Enter seller name', max_length=30, null=True),
        ),
    ]
