# Generated by Django 4.1.7 on 2023-03-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_salesman_last_name_salesman_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_descript',
            field=models.TextField(blank=True, help_text='Enter a description of the pizza', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_name',
            field=models.CharField(blank=True, help_text='Enter pizza name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_weight',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
