# Generated by Django 4.1.7 on 2023-03-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pizza_pizza_descript_pizza_pizza_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_weight',
            field=models.CharField(blank=True, help_text='Enter weight', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.CharField(help_text='Enter prise', max_length=10),
        ),
    ]
