# Generated by Django 4.1.7 on 2023-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_pizza_pizza_weight_alter_pizza_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='first_name',
            field=models.CharField(blank=True, help_text='Enter seller first name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='last_name',
            field=models.CharField(blank=True, help_text='Enter seller last name', max_length=30, null=True),
        ),
    ]
