# Generated by Django 4.1.7 on 2023-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_salesman_first_name_alter_salesman_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.CharField(help_text='Enter price', max_length=10),
        ),
    ]
